development:
  access_key_id: L7QG0NXV8NR5QRWE2THV
  secret_access_key: jtzOJezlwY7KqVNJ+BauPkI+t6Wcx1GfYOLBf5O2

production:
  access_key_id: L7QG0NXV8NR5QRWE2THV
  secret_access_key: jtzOJezlwY7KqVNJ+BauPkI+t6Wcx1GfYOLBf5O2